Closes #9 by adding the content-type and latest options to the list-downloads command.

diff --git a/commands/list-downloads/script b/commands/list-downloads/script
--- a/commands/list-downloads/script
+++ b/commands/list-downloads/script
@@ -1,23 +1,30 @@
 #!/usr/bin/env bash
 #
-#/ command: github:list-downloads: ""List downloads for a repository""
+#/ command: github:list-downloads: "List downloads for a repository"
 #
-#/ usage: rerun github:list-downloads  --owner|-o <>  --repository|-r <> [ --url|-u <https://api.github.com>] 
+#/ usage: rerun github:list-downloads  --owner <>  --repository <> [ --url <https://api.github.com>] [ --content-type <application/x-rpm>] [ --latest <false>] 
 #
-#/ variables: OWNER REPOSITORY URL
+#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option variables: OWNER REPOSITORY URL CONTENT_TYPE LATEST
 
 # Read module function library.
-. $RERUN_MODULE_DIR/lib/functions.sh || { 
-  echo >&2 "Failed loading function library" ; exit 1 ; 
+. $RERUN_MODULE_DIR/lib/functions.sh || {
+  echo >&2 "Failed loading function library." ; exit 1 ;
 }
+
+# Error handling
+# ---------------
+# * Trap calls `rerun_die` with standard message.
+# * Exit upon command errors or accessing unset variables.
+#   * See [set](http://ss64.com/bash/set.html)
+trap 'rerun_die $? "*** command failed: github:list-downloads. ***"' ERR
+set -o nounset -o pipefail
 
 # Parse the command options.
-[ -r $RERUN_MODULE_DIR/commands/list-downloads/options.sh ] && {
-  . $RERUN_MODULE_DIR/commands/list-downloads/options.sh || exit 2 ;
+[[ -r $RERUN_MODULE_DIR/commands/list-downloads/options.sh ]] && {
+    . $RERUN_MODULE_DIR/commands/list-downloads/options.sh || rerun_die "Failed loading options parser."
+    rerun_options_parse "$@"
 }
-
-# Exit immediately upon non-zero exit. See [set](http://ss64.com/bash/set.html)
-set -e -o pipefail
 
 # ------------------------------
 # Your implementation goes here.
@@ -35,7 +42,12 @@ then
 fi
 
 # Display the names and identifiers.
-cat ${RESPONSE} | jq -r '.[] | .name + ":" + (.id | tostring )'
+if [[ $LATEST = "false" ]]
+then
+  cat ${RESPONSE} | jq -r '.[] | .name + ":" + .content_type + ":" + (.id | tostring)' | grep ":${CONTENT_TYPE}:" | sort -nt: -k3
+else
+  cat ${RESPONSE} | jq -r '.[] | .name + ":" + .content_type + ":" + (.id | tostring)' | grep ":${CONTENT_TYPE}:" | sort -nt: -k3 | tail -1
+fi
 
 rm -f ${RESPONSE}
 
