Fixes #13 by updating lib/functions.sh and all the command headers to conform with the latest Rerun templates.

diff --git a/commands/delete-repo-deploy-keys/script b/commands/delete-repo-deploy-keys/script
--- a/commands/delete-repo-deploy-keys/script
+++ b/commands/delete-repo-deploy-keys/script
@@ -1,35 +1,67 @@
 #!/usr/bin/env bash
-#
-#/ command: github:delete-repo-deploy-keys: "Delete repository deploy key(s) matching the specified title"
-#
-#/ usage: rerun github:delete-repo-deploy-keys  --owner <>  --repository <> [ --title <${USER}@${HOSTNAME}>] [ --api-url <https://api.github.com>] [ --authorization-file <$HOME/.rerun/github.authorization>] 
-#
-#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
-#/ option variables: OWNER REPOSITORY TITLE API_URL AUTHORIZATION_FILE
 
-# Read module function library.
-. $RERUN_MODULE_DIR/lib/functions.sh || { 
+# To implement this command, edit the "Command implementation" section below. 
+
+# Usage
+# -----
+
+# Comments prefixed with `#/` are managed by stubbs.
+# The `command` and `usage` comments describe the command
+# and show its options.
+# 
+#/ command: github:delete-repo-deploy-keys: "Delete repository deploy key(s) matching the specified title"
+#/ usage: rerun github:delete-repo-deploy-keys  --owner <>  --repository <> [ --title <${USER}@${HOSTNAME}>] [ --api-url <https://api.github.com>] [ --authorization-file <$HOME/.rerun/github.authorization>] 
+
+# Load common functions
+# ---------------------
+
+# Load the function library for this module.
+# This loads rerun functions, too.
+. $RERUN_MODULE_DIR/lib/functions.sh delete-repo-deploy-keys || { 
   echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
 # Error handling
 # ---------------
-# * Trap calls `rerun_die` with standard message.
-# * Exit upon command errors or accessing unset variables.
-#   * See [set](http://ss64.com/bash/set.html)
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
 trap 'rerun_die $? "*** command failed: github:delete-repo-deploy-keys. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
 set -o nounset -o pipefail
 
-# Parse the command options.
-[[ -r $RERUN_MODULE_DIR/commands/delete-repo-deploy-keys/options.sh ]] && {
-    . $RERUN_MODULE_DIR/commands/delete-repo-deploy-keys/options.sh || rerun_die "Failed loading options parser."
-    rerun_options_parse "$@"
-}
+# Command variables
+# -----------------
+
+# This command script can access the following variables
+# declared by `rerun` or by the option parser function.
+
+#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option-variables: OWNER REPOSITORY TITLE API_URL AUTHORIZATION_FILE
+
+# The `rerun_options_parse` function processes the command line
+# arguments. Each accepted command line flag results in setting 
+# one the corresponding option variables.
+
+rerun_options_parse "$@"
 
 
-# ------------------------------
-# Your implementation goes here.
-# ------------------------------
+# Command implementation
+# ----------------------
+
+# - - -
+# Put the command implementation here.
+# - - -
 
 # Run through the list of matching titles.
 for ID in $(rerun github:list-repo-deploy-keys --owner ${OWNER} --repository ${REPOSITORY} | grep "^$TITLE:" | cut -d: -f2)
